sudo: false
language: python
python: "3.6"
notifications:
  on_success: never
  on_failure: never
before_script:
- pip install tox

matrix:
  include:
  - env: TOXENV=django2.0,django1.11,flake,codecov
  - env: TOXENV=djangolatest
  - python: "3.5"
    env: TOXENV=django2.0,django1.11
  - python: "3.4"
    env: TOXENV=django2.0,django1.11
  allow_failures:
  - env: TOXENV=djangolatest 

script: tox -e $TOXENV
