sudo: false
language: python
python: "3.7"
notifications:
  on_success: never
  on_failure: never
before_script:
- pip install tox

matrix:
  include:
  - env: TOXENV=django2.1,django2.0,flake,codecov
    sudo: true
    dist: xenial
  - env: TOXENV=djangolatest
    sudo: true
    dist: xenial
  - python: "3.6"
    env: TOXENV=django2.1,django2.0
  - python: "3.5"
    env: TOXENV=django2.1,django2.0
  allow_failures:
  - env: TOXENV=djangolatest

script: tox -e $TOXENV
