sudo: false
language: python
python:
  - 3.6
notifications:
  on_success: never
  on_failure: never
branches:
  except:
  - heroku
before_script:
- pip install tox
jobs:
  include:
    - stage: test
      script: tox -e django_111
    - script: tox -e django_110
    - script: tox -e flake
    - script: tox -e codecov
    - stage: test
      python: 3.5
      script: tox -e django_111
    - stage: test
      python: 3.5
      script: tox -e django_110
    - stage: deploy
      python: 2.7
      before_script: skip
      script: skip
      before_deploy:
      - rm demo -rf
      - mv heroku/requirements.txt .
      - mv heroku/Procfile .
      deploy:
        provider: heroku
        app: silverstrike 
        on: master
        run:
        - python heroku/manage.py migrate --noinput
        skip_cleanup: true
        api_key:
          secure: VEsD1LD8Xdor3ccIu8l00H1RAApICqe5HWhZSxGsbw/Boo5fXh8Rp+13TCLY3Y3pgbGWT33UoDa6nj0K5RP//L8n5wh5OIXi7/OPg1mKG1jZP019dHKBX+lQvwjfVlUy2NJMYpI1z8cN7VeZtVcZzjRewTX7NJPysa4oN1CDWSpyC+H6cuBWpQY5ge6FXYOPx2k/ZXgwUu/SIoJQ/vZuKJNZ3GlLWjaidT+zDrFMywlqwKnlrPfCf3qQG28CuxpNyqQ6xDsSUHPdNL52DYjPpx3256XCp6px3n+fFf9C6odjBKN9pb20MgVheKqga6pcXCM6OzMLLsYAqrMlHAExR1d4xIEA3eQpOHND1Pedll/63uX3U0nr/eQOpg/5nSNf+uVlp/guKQy3aSre8XdS3vZ+aIKwxh50S+rr8gE8fw4VHWwDt6syLClpQGKhFYhCXkU1Wzyoo5PgcgGkCIp1w4E1d8E46hUxrilgPjLe+VqaygI/ZjEmNR8mylfzEHNcHd6TkAzfeNZ1fCK+b9ZKSPkaWmH9Ax5fGjoicBEnADWg/C1C42j4PsDjqDKFOgNEJg50UrfDJMck6C5YWdpwFviN4LMZyKJh9uMWfwc6OuLCGmgs9jgSAV03A7nNyO634vXjR1eTEyUwHbvOJ6065p47ifO6pSY4vDHFJ52oQUo=

