# Generated by Django 2.2b1 on 2019-06-29 21:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0007_auto_20181230_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Transfer')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Transfer'), (4, 'Reconcile')]),
        ),
        migrations.CreateModel(
            name='InvestmentOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('type', models.IntegerField(choices=[(1, 'Buy'), (2, 'Sell'), (3, 'Dividend')])),
                ('name', models.CharField(max_length=64)),
                ('isin', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('price', models.FloatField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_transactions', to='silverstrike.Account')),
            ],
            options={
                'ordering': ['-date', 'name'],
            },
        ),
    ]
