# Generated by Django 2.2rc1 on 2019-08-19 22:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0007_auto_20181230_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_ptr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Transfer')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Transfer'), (4, 'Reconcile')]),
        ),
        migrations.CreateModel(
            name='InvestmentOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('operation_type', models.IntegerField(choices=[(0, 'Buy'), (1, 'Sell'), (2, 'Dividend')], default=0)),
                ('isin', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_transactions', to='silverstrike.Account')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='silverstrike.Transaction')),
            ],
        ),
    ]
