# Generated by Django 2.2b1 on 2019-08-23 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0008_auto_20190819_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=64)),
                ('quantity', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silverstrike.Account')),
            ],
        ),
    ]
