# Generated by Django 2.2b1 on 2019-06-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0008_auto_20190629_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentoperation',
            name='category',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
