# Generated by Django 2.2b1 on 2019-07-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0009_auto_20190629_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentoperation',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='investmentoperation',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
