# Generated by Django 2.2b1 on 2019-08-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0009_securityquantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=64)),
                ('ticker', models.CharField(max_length=64)),
                ('exchange', models.CharField(max_length=64)),
                ('currency', models.CharField(max_length=3)),
                ('security_type', models.IntegerField(choices=[(0, 'Stock'), (1, 'REIT'), (2, 'Bond')], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='investmentoperation',
            name='isin',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='securityquantity',
            name='isin',
            field=models.CharField(max_length=12),
        ),
    ]
