# Generated by Django 2.2b1 on 2019-07-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0010_auto_20190710_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentoperation',
            options={},
        ),
        migrations.RenameField(
            model_name='investmentoperation',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='investmentoperation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='investmentoperation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='investmentoperation',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='investmentoperation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='investmentoperation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='investmentoperation',
            name='type',
        ),
        migrations.AddField(
            model_name='investmentoperation',
            name='operation_type',
            field=models.IntegerField(choices=[(0, 'Buy'), (1, 'Sell'), (2, 'Dividend')], default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_ptr',
            field=models.IntegerField(null=True),
        ),
    ]
