# Generated by Django 2.2b1 on 2019-08-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0010_auto_20190828_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitydetails',
            name='ter',
            field=models.FloatField(default=0.0),
        ),
    ]
