# Generated by Django 2.2b1 on 2019-09-03 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0011_securitydetails_ter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=12)),
                ('allocation', models.FloatField(default=0.0)),
                ('region_id', models.IntegerField(choices=[(2, 'United Kingdom'), (3, 'Euro Zone'), (8, 'Japan'), (7, 'Middle East/Asia'), (6, 'Africa'), (11, 'Asia Emerging'), (4, 'Europe Ex-EZ'), (9, 'Australasia'), (0, 'North America'), (10, 'Asia Developed'), (5, 'Europe Emerging'), (1, 'Latin America')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=12)),
                ('date', models.DateField(default=datetime.date.today)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
