# Generated by Django 2.2b1 on 2019-09-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0012_securitydistribution_securityprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitydistribution',
            name='region_id',
            field=models.IntegerField(choices=[(2, 'United Kingdom'), (4, 'Europe Ex-EZ'), (9, 'Australasia'), (6, 'Africa'), (7, 'Middle East/Asia'), (8, 'Japan'), (10, 'Asia Developed'), (5, 'Europe Emerging'), (1, 'Latin America'), (0, 'North America'), (11, 'Asia Emerging'), (3, 'Euro Zone')], default=3),
        ),
        migrations.AlterUniqueTogether(
            name='securitydistribution',
            unique_together={('isin', 'region_id')},
        ),
    ]
