# Generated by Django 2.2.5 on 2019-09-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0013_auto_20190904_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityRegionTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.IntegerField(choices=[(0, 'North America'), (1, 'Latin America'), (2, 'United Kingdom'), (3, 'Euro Zone'), (4, 'Europe Ex-EZ'), (5, 'Europe Emerging'), (6, 'Africa'), (7, 'Middle East/Asia'), (8, 'Japan'), (9, 'Australasia'), (10, 'Asia Developed'), (11, 'Asia Emerging')], default=3)),
                ('allocation', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityTypeTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_type', models.IntegerField(choices=[(0, 'Stock'), (1, 'REIT'), (2, 'Bond')], default=0)),
                ('allocation', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='securitydistribution',
            name='region_id',
            field=models.IntegerField(choices=[(0, 'North America'), (1, 'Latin America'), (2, 'United Kingdom'), (3, 'Euro Zone'), (4, 'Europe Ex-EZ'), (5, 'Europe Emerging'), (6, 'Africa'), (7, 'Middle East/Asia'), (8, 'Japan'), (9, 'Australasia'), (10, 'Asia Developed'), (11, 'Asia Emerging')], default=3),
        ),
    ]
