# Generated by Django 2.2.5 on 2019-09-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0014_auto_20190910_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityBondMaturityTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maturity_id', models.IntegerField(choices=[(0, '1-3Y'), (1, '3-5Y'), (2, '5-7Y'), (3, '7-10Y'), (4, '10-15Y'), (5, '15-20Y'), (6, '20-30Y'), (7, '30+')], default=0)),
                ('allocation', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityBondRegionTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.IntegerField(choices=[(0, 'United States'), (1, 'Europe')], default=1)),
                ('allocation', models.FloatField(default=0.0)),
            ],
        ),
    ]
