# Generated by Django 2.2.5 on 2019-09-15 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0015_securitybondmaturitytarget_securitybondregiontarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('original_operation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silverstrike.InvestmentOperation')),
            ],
        ),
    ]
