# Generated by Django 2.2.5 on 2019-09-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0017_securitybondmaturity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securitybondmaturity',
            old_name='maturity',
            new_name='maturity_id',
        ),
        migrations.AlterUniqueTogether(
            name='securitybondmaturity',
            unique_together={('isin', 'maturity_id')},
        ),
    ]
