# Generated by Django 2.2.5 on 2019-11-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0019_currencypreference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencypreference',
            old_name='user_id',
            new_name='user',
        ),
    ]
