# Generated by Django 3.0.4 on 2020-03-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0020_auto_20191103_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitydetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='securitydetails',
            name='isin',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
