# Generated by Django 3.0.4 on 2020-03-25 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0021_auto_20200319_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentoperation',
            name='isin',
            field=models.ForeignKey(default='NO_ISIN', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='security_isin', to='silverstrike.SecurityDetails'),
        ),
    ]
