# Generated by Django 3.0.4 on 2020-03-25 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0022_auto_20200325_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityquantity',
            name='isin',
            field=models.ForeignKey(default='NO_ISIN', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='asset_isin', to='silverstrike.SecurityDetails'),
        ),
    ]
