# Generated by Django 3.0.4 on 2020-03-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0023_auto_20200325_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentoperation',
            old_name='isin',
            new_name='security',
        ),
    ]
