# Generated by Django 3.0.4 on 2020-03-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0024_auto_20200326_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securityquantity',
            old_name='isin',
            new_name='security',
        ),
    ]
