# Generated by Django 3.0.4 on 2020-03-26 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0025_auto_20200326_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitybondmaturity',
            name='security',
            field=models.ForeignKey(default='NO_ISIN', on_delete=django.db.models.deletion.CASCADE, related_name='security_bond_id', to='silverstrike.SecurityDetails'),
        ),
        migrations.AddField(
            model_name='securitydistribution',
            name='security',
            field=models.ForeignKey(default='NO_ISIN', on_delete=django.db.models.deletion.CASCADE, related_name='security_id', to='silverstrike.SecurityDetails'),
        ),
        migrations.AlterUniqueTogether(
            name='securitybondmaturity',
            unique_together={('security', 'maturity_id')},
        ),
        migrations.AlterUniqueTogether(
            name='securitydistribution',
            unique_together={('security', 'region_id')},
        ),
        migrations.RemoveField(
            model_name='securitybondmaturity',
            name='isin',
        ),
        migrations.RemoveField(
            model_name='securitydistribution',
            name='isin',
        ),
    ]
