# Generated by Django 3.0.4 on 2020-04-11 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0027_investmentoperation_exchange_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPairPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=6)),
                ('date', models.DateField(default=datetime.date.today)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
